name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy Backend to ECS
        run: |
          aws ecs update-service --cluster backend-cluster --service backend-service --force-new-deployment

      - name: Deploy Frontend to ECS
        run: |
          aws ecs update-service --cluster frontend-cluster --service frontend-service --force-new-deployment
