name: CI - Test and Push Images

on:
  push:
    branches: [develop]

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend tests
      working-directory: ./backend
      run: pytest tests/

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm run test || true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push backend image to ECR
      working-directory: ./backend
      run: |
        docker build -t ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }} .
        docker push ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}

    - name: Build and push frontend image to ECR
      working-directory: ./frontend
      run: |
        docker build -t ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }} .
        docker push ${{ secrets.ECR_FRONTEND_REPO }}:${{ github.sha }}

